<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class GeographySeeder extends Seeder
{
    public function run(): void
    {
        // ── Geopolitical Regions ──────────────────────────────────────────────
        $regions = [
            ['id' => 1, 'name' => 'South-West',   'code' => 'SW'],
            ['id' => 2, 'name' => 'South-East',   'code' => 'SE'],
            ['id' => 3, 'name' => 'South-South',  'code' => 'SS'],
            ['id' => 4, 'name' => 'North-West',   'code' => 'NW'],
            ['id' => 5, 'name' => 'North-East',   'code' => 'NE'],
            ['id' => 6, 'name' => 'North-Central','code' => 'NC'],
        ];
        foreach ($regions as &$r) { $r['created_at'] = $r['updated_at'] = now(); }
        DB::table('regions')->upsert($regions, ['id'], ['name', 'code', 'updated_at']);

        // ── States (36 + FCT) ─────────────────────────────────────────────────
        // Lagos is id=1 so existing department/office lga_id references remain valid.
        $states = [
            // South-West (region 1)
            ['id' =>  1, 'region_id' => 1, 'name' => 'Lagos',     'code' => 'LA'],
            ['id' =>  2, 'region_id' => 1, 'name' => 'Ogun',      'code' => 'OG'],
            ['id' =>  3, 'region_id' => 1, 'name' => 'Ondo',      'code' => 'ON'],
            ['id' =>  4, 'region_id' => 1, 'name' => 'Osun',      'code' => 'OS'],
            ['id' =>  5, 'region_id' => 1, 'name' => 'Oyo',       'code' => 'OY'],
            ['id' =>  6, 'region_id' => 1, 'name' => 'Ekiti',     'code' => 'EK'],
            // South-East (region 2)
            ['id' =>  7, 'region_id' => 2, 'name' => 'Anambra',   'code' => 'AN'],
            ['id' =>  8, 'region_id' => 2, 'name' => 'Enugu',     'code' => 'EN'],
            ['id' =>  9, 'region_id' => 2, 'name' => 'Imo',       'code' => 'IM'],
            ['id' => 10, 'region_id' => 2, 'name' => 'Abia',      'code' => 'AB'],
            ['id' => 11, 'region_id' => 2, 'name' => 'Ebonyi',    'code' => 'EB'],
            // South-South (region 3)
            ['id' => 12, 'region_id' => 3, 'name' => 'Rivers',    'code' => 'RI'],
            ['id' => 13, 'region_id' => 3, 'name' => 'Delta',     'code' => 'DE'],
            ['id' => 14, 'region_id' => 3, 'name' => 'Edo',       'code' => 'ED'],
            ['id' => 15, 'region_id' => 3, 'name' => 'Cross River','code' => 'CR'],
            ['id' => 16, 'region_id' => 3, 'name' => 'Akwa Ibom', 'code' => 'AK'],
            ['id' => 17, 'region_id' => 3, 'name' => 'Bayelsa',   'code' => 'BY'],
            // North-West (region 4)
            ['id' => 18, 'region_id' => 4, 'name' => 'Kaduna',    'code' => 'KD'],
            ['id' => 19, 'region_id' => 4, 'name' => 'Kano',      'code' => 'KN'],
            ['id' => 20, 'region_id' => 4, 'name' => 'Katsina',   'code' => 'KT'],
            ['id' => 21, 'region_id' => 4, 'name' => 'Jigawa',    'code' => 'JI'],
            ['id' => 22, 'region_id' => 4, 'name' => 'Kebbi',     'code' => 'KB'],
            ['id' => 23, 'region_id' => 4, 'name' => 'Sokoto',    'code' => 'SO'],
            ['id' => 24, 'region_id' => 4, 'name' => 'Zamfara',   'code' => 'ZA'],
            // North-East (region 5)
            ['id' => 25, 'region_id' => 5, 'name' => 'Adamawa',   'code' => 'AD'],
            ['id' => 26, 'region_id' => 5, 'name' => 'Bauchi',    'code' => 'BA'],
            ['id' => 27, 'region_id' => 5, 'name' => 'Borno',     'code' => 'BO'],
            ['id' => 28, 'region_id' => 5, 'name' => 'Gombe',     'code' => 'GO'],
            ['id' => 29, 'region_id' => 5, 'name' => 'Taraba',    'code' => 'TA'],
            ['id' => 30, 'region_id' => 5, 'name' => 'Yobe',      'code' => 'YO'],
            // North-Central (region 6)
            ['id' => 31, 'region_id' => 6, 'name' => 'Benue',     'code' => 'BE'],
            ['id' => 32, 'region_id' => 6, 'name' => 'FCT (Abuja)','code' => 'FC'],
            ['id' => 33, 'region_id' => 6, 'name' => 'Kogi',      'code' => 'KO'],
            ['id' => 34, 'region_id' => 6, 'name' => 'Kwara',     'code' => 'KW'],
            ['id' => 35, 'region_id' => 6, 'name' => 'Nasarawa',  'code' => 'NA'],
            ['id' => 36, 'region_id' => 6, 'name' => 'Niger',     'code' => 'NI'],
            ['id' => 37, 'region_id' => 6, 'name' => 'Plateau',   'code' => 'PL'],
        ];
        foreach ($states as &$s) { $s['created_at'] = $s['updated_at'] = now(); }
        DB::table('states')->upsert($states, ['id'], ['region_id', 'name', 'code', 'updated_at']);

        // ── LGAs ─────────────────────────────────────────────────────────────
        // LGA id=1 = Alimosho (Lagos) so departments/offices referencing lga_id=1 remain valid.
        $lgasByState = [
            // Lagos (state 1) — 20 LGAs — Alimosho first (id=1)
            1 => [
                ['id' =>   1, 'name' => 'Alimosho',          'code' => 'ALM', 'address' => 'Alimosho LGA Secretariat, Idimu Road, Lagos'],
                ['id' =>   2, 'name' => 'Agege',             'code' => 'AGG', 'address' => 'Agege LGA Secretariat, Lagos'],
                ['id' =>   3, 'name' => 'Ajeromi-Ifelodun',  'code' => 'AJR', 'address' => 'Ajeromi-Ifelodun LGA Secretariat, Lagos'],
                ['id' =>   4, 'name' => 'Amuwo-Odofin',      'code' => 'AMO', 'address' => 'Amuwo-Odofin LGA Secretariat, Lagos'],
                ['id' =>   5, 'name' => 'Apapa',             'code' => 'APP', 'address' => 'Apapa LGA Secretariat, Lagos'],
                ['id' =>   6, 'name' => 'Badagry',           'code' => 'BDG', 'address' => 'Badagry LGA Secretariat, Lagos'],
                ['id' =>   7, 'name' => 'Epe',               'code' => 'EPE', 'address' => 'Epe LGA Secretariat, Lagos'],
                ['id' =>   8, 'name' => 'Eti-Osa',           'code' => 'ETO', 'address' => 'Eti-Osa LGA Secretariat, Lagos'],
                ['id' =>   9, 'name' => 'Ibeju-Lekki',       'code' => 'IBL', 'address' => 'Ibeju-Lekki LGA Secretariat, Lagos'],
                ['id' =>  10, 'name' => 'Ifako-Ijaye',       'code' => 'IFJ', 'address' => 'Ifako-Ijaye LGA Secretariat, Lagos'],
                ['id' =>  11, 'name' => 'Ikeja',             'code' => 'IKJ', 'address' => 'Ikeja LGA Secretariat, Lagos'],
                ['id' =>  12, 'name' => 'Ikorodu',           'code' => 'IKR', 'address' => 'Ikorodu LGA Secretariat, Lagos'],
                ['id' =>  13, 'name' => 'Kosofe',            'code' => 'KSF', 'address' => 'Kosofe LGA Secretariat, Lagos'],
                ['id' =>  14, 'name' => 'Lagos Island',      'code' => 'LGI', 'address' => 'Lagos Island LGA Secretariat, Lagos'],
                ['id' =>  15, 'name' => 'Lagos Mainland',    'code' => 'LGM', 'address' => 'Lagos Mainland LGA Secretariat, Lagos'],
                ['id' =>  16, 'name' => 'Mushin',            'code' => 'MSH', 'address' => 'Mushin LGA Secretariat, Lagos'],
                ['id' =>  17, 'name' => 'Ojo',               'code' => 'OJO', 'address' => 'Ojo LGA Secretariat, Lagos'],
                ['id' =>  18, 'name' => 'Oshodi-Isolo',      'code' => 'OSH', 'address' => 'Oshodi-Isolo LGA Secretariat, Lagos'],
                ['id' =>  19, 'name' => 'Shomolu',           'code' => 'SHM', 'address' => 'Shomolu LGA Secretariat, Lagos'],
                ['id' =>  20, 'name' => 'Surulere',          'code' => 'SUR', 'address' => 'Surulere LGA Secretariat, Lagos'],
            ],
            // Ogun (state 2) — 20 LGAs
            2 => [
                ['id' =>  21, 'name' => 'Abeokuta North',      'code' => 'ABN'],
                ['id' =>  22, 'name' => 'Abeokuta South',      'code' => 'ABS'],
                ['id' =>  23, 'name' => 'Ado-Odo/Ota',         'code' => 'ADO'],
                ['id' =>  24, 'name' => 'Egbado North',        'code' => 'EGN'],
                ['id' =>  25, 'name' => 'Egbado South',        'code' => 'EGS'],
                ['id' =>  26, 'name' => 'Ewekoro',             'code' => 'EWK'],
                ['id' =>  27, 'name' => 'Ifo',                 'code' => 'IFO'],
                ['id' =>  28, 'name' => 'Ijebu East',          'code' => 'IJE'],
                ['id' =>  29, 'name' => 'Ijebu North',         'code' => 'IJN'],
                ['id' =>  30, 'name' => 'Ijebu North East',    'code' => 'IJX'],
                ['id' =>  31, 'name' => 'Ijebu Ode',           'code' => 'IJO'],
                ['id' =>  32, 'name' => 'Ikenne',              'code' => 'IKN'],
                ['id' =>  33, 'name' => 'Imeko Afon',          'code' => 'IMA'],
                ['id' =>  34, 'name' => 'Ipokia',              'code' => 'IPK'],
                ['id' =>  35, 'name' => 'Obafemi Owode',       'code' => 'OBF'],
                ['id' =>  36, 'name' => 'Odeda',               'code' => 'ODD'],
                ['id' =>  37, 'name' => 'Odogbolu',            'code' => 'ODG'],
                ['id' =>  38, 'name' => 'Ogun Waterside',      'code' => 'OGW'],
                ['id' =>  39, 'name' => 'Remo North',          'code' => 'RMN'],
                ['id' =>  40, 'name' => 'Shagamu',             'code' => 'SGM'],
            ],
            // Ondo (state 3) — 18 LGAs
            3 => [
                ['id' =>  41, 'name' => 'Akoko North East',    'code' => 'ANE'],
                ['id' =>  42, 'name' => 'Akoko North West',    'code' => 'ANW'],
                ['id' =>  43, 'name' => 'Akoko South East',    'code' => 'ASE'],
                ['id' =>  44, 'name' => 'Akoko South West',    'code' => 'ASW'],
                ['id' =>  45, 'name' => 'Akure North',         'code' => 'AKN'],
                ['id' =>  46, 'name' => 'Akure South',         'code' => 'AKS'],
                ['id' =>  47, 'name' => 'Ese Odo',             'code' => 'ESO'],
                ['id' =>  48, 'name' => 'Idanre',              'code' => 'IDN'],
                ['id' =>  49, 'name' => 'Ifedore',             'code' => 'IFD'],
                ['id' =>  50, 'name' => 'Ilaje',               'code' => 'ILJ'],
                ['id' =>  51, 'name' => 'Ile Oluji/Okeigbo',   'code' => 'ILO'],
                ['id' =>  52, 'name' => 'Irele',               'code' => 'IRL'],
                ['id' =>  53, 'name' => 'Odigbo',              'code' => 'ODI'],
                ['id' =>  54, 'name' => 'Okitipupa',           'code' => 'OKT'],
                ['id' =>  55, 'name' => 'Ondo East',           'code' => 'ONE'],
                ['id' =>  56, 'name' => 'Ondo West',           'code' => 'ONW'],
                ['id' =>  57, 'name' => 'Ose',                 'code' => 'OSE'],
                ['id' =>  58, 'name' => 'Owo',                 'code' => 'OWO'],
            ],
            // Osun (state 4) — 30 LGAs
            4 => [
                ['id' =>  59, 'name' => 'Aiyedaade',           'code' => 'AYD'],
                ['id' =>  60, 'name' => 'Aiyedire',            'code' => 'AYR'],
                ['id' =>  61, 'name' => 'Atakumosa East',      'code' => 'ATE'],
                ['id' =>  62, 'name' => 'Atakumosa West',      'code' => 'ATW'],
                ['id' =>  63, 'name' => 'Boluwaduro',          'code' => 'BLW'],
                ['id' =>  64, 'name' => 'Boripe',              'code' => 'BRP'],
                ['id' =>  65, 'name' => 'Ede North',           'code' => 'EDN'],
                ['id' =>  66, 'name' => 'Ede South',           'code' => 'EDS'],
                ['id' =>  67, 'name' => 'Egbedore',            'code' => 'EGB'],
                ['id' =>  68, 'name' => 'Ejigbo',              'code' => 'EJG'],
                ['id' =>  69, 'name' => 'Ife Central',         'code' => 'IFC'],
                ['id' =>  70, 'name' => 'Ife East',            'code' => 'IFE'],
                ['id' =>  71, 'name' => 'Ife North',           'code' => 'IFN'],
                ['id' =>  72, 'name' => 'Ife South',           'code' => 'IFS'],
                ['id' =>  73, 'name' => 'Ifedayo',             'code' => 'IFY'],
                ['id' =>  74, 'name' => 'Ifelodun',            'code' => 'IFU'],
                ['id' =>  75, 'name' => 'Ila',                 'code' => 'ILA'],
                ['id' =>  76, 'name' => 'Ilesa East',          'code' => 'ILE'],
                ['id' =>  77, 'name' => 'Ilesa West',          'code' => 'ILW'],
                ['id' =>  78, 'name' => 'Irepodun',            'code' => 'IRE'],
                ['id' =>  79, 'name' => 'Irewole',             'code' => 'IRW'],
                ['id' =>  80, 'name' => 'Isokan',              'code' => 'ISK'],
                ['id' =>  81, 'name' => 'Iwo',                 'code' => 'IWO'],
                ['id' =>  82, 'name' => 'Obokun',              'code' => 'OBK'],
                ['id' =>  83, 'name' => 'Odo Otin',            'code' => 'ODT'],
                ['id' =>  84, 'name' => 'Ola Oluwa',           'code' => 'OLO'],
                ['id' =>  85, 'name' => 'Olorunda',            'code' => 'OLR'],
                ['id' =>  86, 'name' => 'Oriade',              'code' => 'ORD'],
                ['id' =>  87, 'name' => 'Orolu',               'code' => 'ORL'],
                ['id' =>  88, 'name' => 'Osogbo',              'code' => 'OSG'],
            ],
            // Oyo (state 5) — 33 LGAs
            5 => [
                ['id' =>  89, 'name' => 'Afijio',              'code' => 'AFJ'],
                ['id' =>  90, 'name' => 'Akinyele',            'code' => 'AKY'],
                ['id' =>  91, 'name' => 'Atiba',               'code' => 'ATB'],
                ['id' =>  92, 'name' => 'Atisbo',              'code' => 'ATS'],
                ['id' =>  93, 'name' => 'Egbeda',              'code' => 'EGB'],
                ['id' =>  94, 'name' => 'Ibadan North',        'code' => 'IBN'],
                ['id' =>  95, 'name' => 'Ibadan North East',   'code' => 'IBE'],
                ['id' =>  96, 'name' => 'Ibadan North West',   'code' => 'IBW'],
                ['id' =>  97, 'name' => 'Ibadan South East',   'code' => 'ISE'],
                ['id' =>  98, 'name' => 'Ibadan South West',   'code' => 'ISW'],
                ['id' =>  99, 'name' => 'Ibarapa Central',     'code' => 'IBC'],
                ['id' => 100, 'name' => 'Ibarapa East',        'code' => 'IBR'],
                ['id' => 101, 'name' => 'Ibarapa North',       'code' => 'IBX'],
                ['id' => 102, 'name' => 'Ido',                 'code' => 'IDO'],
                ['id' => 103, 'name' => 'Irepo',               'code' => 'IRP'],
                ['id' => 104, 'name' => 'Iseyin',              'code' => 'ISY'],
                ['id' => 105, 'name' => 'Itesiwaju',           'code' => 'ITS'],
                ['id' => 106, 'name' => 'Iwajowa',             'code' => 'IWJ'],
                ['id' => 107, 'name' => 'Kajola',              'code' => 'KJL'],
                ['id' => 108, 'name' => 'Lagelu',              'code' => 'LGL'],
                ['id' => 109, 'name' => 'Ogbomosho North',     'code' => 'OGN'],
                ['id' => 110, 'name' => 'Ogbomosho South',     'code' => 'OGS'],
                ['id' => 111, 'name' => 'Ogo Oluwa',           'code' => 'OGL'],
                ['id' => 112, 'name' => 'Olorunsogo',          'code' => 'OLR'],
                ['id' => 113, 'name' => 'Oluyole',             'code' => 'OLY'],
                ['id' => 114, 'name' => 'Ona Ara',             'code' => 'ONA'],
                ['id' => 115, 'name' => 'Orelope',             'code' => 'ORL'],
                ['id' => 116, 'name' => 'Orire',               'code' => 'ORR'],
                ['id' => 117, 'name' => 'Oyo East',            'code' => 'OYE'],
                ['id' => 118, 'name' => 'Oyo West',            'code' => 'OYW'],
                ['id' => 119, 'name' => 'Saki East',           'code' => 'SKE'],
                ['id' => 120, 'name' => 'Saki West',           'code' => 'SKW'],
                ['id' => 121, 'name' => 'Surulere',            'code' => 'SRL'],
            ],
            // Ekiti (state 6) — 16 LGAs
            6 => [
                ['id' => 122, 'name' => 'Ado Ekiti',           'code' => 'ADE'],
                ['id' => 123, 'name' => 'Efon',                'code' => 'EFN'],
                ['id' => 124, 'name' => 'Ekiti East',          'code' => 'EKE'],
                ['id' => 125, 'name' => 'Ekiti South West',    'code' => 'EKS'],
                ['id' => 126, 'name' => 'Ekiti West',          'code' => 'EKW'],
                ['id' => 127, 'name' => 'Emure',               'code' => 'EMR'],
                ['id' => 128, 'name' => 'Gbonyin',             'code' => 'GBN'],
                ['id' => 129, 'name' => 'Ido Osi',             'code' => 'IDO'],
                ['id' => 130, 'name' => 'Ijero',               'code' => 'IJR'],
                ['id' => 131, 'name' => 'Ikere',               'code' => 'IKR'],
                ['id' => 132, 'name' => 'Ikole',               'code' => 'IKL'],
                ['id' => 133, 'name' => 'Ilejemeje',           'code' => 'ILJ'],
                ['id' => 134, 'name' => 'Irepodun/Ifelodun',   'code' => 'IRI'],
                ['id' => 135, 'name' => 'Ise/Orun',            'code' => 'ISR'],
                ['id' => 136, 'name' => 'Moba',                'code' => 'MBA'],
                ['id' => 137, 'name' => 'Oye',                 'code' => 'OYE'],
            ],
            // Anambra (state 7) — 21 LGAs
            7 => [
                ['id' => 138, 'name' => 'Aguata',              'code' => 'AGT'],
                ['id' => 139, 'name' => 'Anambra East',        'code' => 'ANE'],
                ['id' => 140, 'name' => 'Anambra West',        'code' => 'ANW'],
                ['id' => 141, 'name' => 'Anaocha',             'code' => 'ANC'],
                ['id' => 142, 'name' => 'Awka North',          'code' => 'AWN'],
                ['id' => 143, 'name' => 'Awka South',          'code' => 'AWS'],
                ['id' => 144, 'name' => 'Ayamelum',            'code' => 'AYM'],
                ['id' => 145, 'name' => 'Dunukofia',           'code' => 'DNK'],
                ['id' => 146, 'name' => 'Ekwusigo',            'code' => 'EKW'],
                ['id' => 147, 'name' => 'Idemili North',       'code' => 'IDN'],
                ['id' => 148, 'name' => 'Idemili South',       'code' => 'IDS'],
                ['id' => 149, 'name' => 'Ihiala',              'code' => 'IHL'],
                ['id' => 150, 'name' => 'Njikoka',             'code' => 'NJK'],
                ['id' => 151, 'name' => 'Nnewi North',         'code' => 'NNN'],
                ['id' => 152, 'name' => 'Nnewi South',         'code' => 'NNS'],
                ['id' => 153, 'name' => 'Ogbaru',              'code' => 'OGB'],
                ['id' => 154, 'name' => 'Onitsha North',       'code' => 'ONN'],
                ['id' => 155, 'name' => 'Onitsha South',       'code' => 'ONS'],
                ['id' => 156, 'name' => 'Orumba North',        'code' => 'ORN'],
                ['id' => 157, 'name' => 'Orumba South',        'code' => 'ORS'],
                ['id' => 158, 'name' => 'Oyi',                 'code' => 'OYI'],
            ],
            // Enugu (state 8) — 17 LGAs
            8 => [
                ['id' => 159, 'name' => 'Aninri',              'code' => 'ANR'],
                ['id' => 160, 'name' => 'Awgu',                'code' => 'AWG'],
                ['id' => 161, 'name' => 'Enugu East',          'code' => 'ENE'],
                ['id' => 162, 'name' => 'Enugu North',         'code' => 'ENN'],
                ['id' => 163, 'name' => 'Enugu South',         'code' => 'ENS'],
                ['id' => 164, 'name' => 'Ezeagu',              'code' => 'EZG'],
                ['id' => 165, 'name' => 'Igbo Etiti',          'code' => 'IGE'],
                ['id' => 166, 'name' => 'Igbo Eze North',      'code' => 'IGN'],
                ['id' => 167, 'name' => 'Igbo Eze South',      'code' => 'IGS'],
                ['id' => 168, 'name' => 'Isi Uzo',             'code' => 'ISU'],
                ['id' => 169, 'name' => 'Nkanu East',          'code' => 'NKE'],
                ['id' => 170, 'name' => 'Nkanu West',          'code' => 'NKW'],
                ['id' => 171, 'name' => 'Nsukka',              'code' => 'NSK'],
                ['id' => 172, 'name' => 'Oji River',           'code' => 'OJR'],
                ['id' => 173, 'name' => 'Udenu',               'code' => 'UDN'],
                ['id' => 174, 'name' => 'Udi',                 'code' => 'UDI'],
                ['id' => 175, 'name' => 'Uzo Uwani',           'code' => 'UZU'],
            ],
            // Imo (state 9) — 27 LGAs
            9 => [
                ['id' => 176, 'name' => 'Aboh Mbaise',         'code' => 'ABM'],
                ['id' => 177, 'name' => 'Ahiazu Mbaise',       'code' => 'AHM'],
                ['id' => 178, 'name' => 'Ehime Mbano',         'code' => 'EHM'],
                ['id' => 179, 'name' => 'Ezinihitte',          'code' => 'EZN'],
                ['id' => 180, 'name' => 'Ideato North',        'code' => 'IDN'],
                ['id' => 181, 'name' => 'Ideato South',        'code' => 'IDS'],
                ['id' => 182, 'name' => 'Ihitte/Uboma',        'code' => 'IHU'],
                ['id' => 183, 'name' => 'Ikeduru',             'code' => 'IKD'],
                ['id' => 184, 'name' => 'Isiala Mbano',        'code' => 'ISM'],
                ['id' => 185, 'name' => 'Isu',                 'code' => 'ISU'],
                ['id' => 186, 'name' => 'Mbaitoli',            'code' => 'MBT'],
                ['id' => 187, 'name' => 'Ngor Okpala',         'code' => 'NGO'],
                ['id' => 188, 'name' => 'Njaba',               'code' => 'NJB'],
                ['id' => 189, 'name' => 'Nkwerre',             'code' => 'NKW'],
                ['id' => 190, 'name' => 'Nwangele',            'code' => 'NWG'],
                ['id' => 191, 'name' => 'Obowo',               'code' => 'OBW'],
                ['id' => 192, 'name' => 'Oguta',               'code' => 'OGT'],
                ['id' => 193, 'name' => 'Ohaji/Egbema',        'code' => 'OHE'],
                ['id' => 194, 'name' => 'Okigwe',              'code' => 'OKG'],
                ['id' => 195, 'name' => 'Onuimo',              'code' => 'ONU'],
                ['id' => 196, 'name' => 'Orlu',                'code' => 'ORL'],
                ['id' => 197, 'name' => 'Orsu',                'code' => 'ORS'],
                ['id' => 198, 'name' => 'Oru East',            'code' => 'ORE'],
                ['id' => 199, 'name' => 'Oru West',            'code' => 'ORW'],
                ['id' => 200, 'name' => 'Owerri Municipal',    'code' => 'OWM'],
                ['id' => 201, 'name' => 'Owerri North',        'code' => 'OWN'],
                ['id' => 202, 'name' => 'Owerri West',         'code' => 'OWW'],
            ],
            // Abia (state 10) — 17 LGAs
            10 => [
                ['id' => 203, 'name' => 'Aba North',           'code' => 'ABN'],
                ['id' => 204, 'name' => 'Aba South',           'code' => 'ABS'],
                ['id' => 205, 'name' => 'Arochukwu',           'code' => 'ARC'],
                ['id' => 206, 'name' => 'Bende',               'code' => 'BND'],
                ['id' => 207, 'name' => 'Ikwuano',             'code' => 'IKW'],
                ['id' => 208, 'name' => 'Isiala Ngwa North',   'code' => 'ISN'],
                ['id' => 209, 'name' => 'Isiala Ngwa South',   'code' => 'ISS'],
                ['id' => 210, 'name' => 'Isuikwuato',          'code' => 'ISU'],
                ['id' => 211, 'name' => 'Obi Ngwa',            'code' => 'OBN'],
                ['id' => 212, 'name' => 'Ohafia',              'code' => 'OHF'],
                ['id' => 213, 'name' => 'Osisioma',            'code' => 'OSS'],
                ['id' => 214, 'name' => 'Ugwunagbo',           'code' => 'UGW'],
                ['id' => 215, 'name' => 'Ukwa East',           'code' => 'UKE'],
                ['id' => 216, 'name' => 'Ukwa West',           'code' => 'UKW'],
                ['id' => 217, 'name' => 'Umuahia North',       'code' => 'UMN'],
                ['id' => 218, 'name' => 'Umuahia South',       'code' => 'UMS'],
                ['id' => 219, 'name' => 'Umu Nneochi',         'code' => 'UMU'],
            ],
            // Ebonyi (state 11) — 13 LGAs
            11 => [
                ['id' => 220, 'name' => 'Abakaliki',           'code' => 'ABK'],
                ['id' => 221, 'name' => 'Afikpo North',        'code' => 'AFN'],
                ['id' => 222, 'name' => 'Afikpo South',        'code' => 'AFS'],
                ['id' => 223, 'name' => 'Ebonyi',              'code' => 'EBN'],
                ['id' => 224, 'name' => 'Ezza North',          'code' => 'EZN'],
                ['id' => 225, 'name' => 'Ezza South',          'code' => 'EZS'],
                ['id' => 226, 'name' => 'Ikwo',                'code' => 'IKW'],
                ['id' => 227, 'name' => 'Ishielu',             'code' => 'ISH'],
                ['id' => 228, 'name' => 'Ivo',                 'code' => 'IVO'],
                ['id' => 229, 'name' => 'Izzi',                'code' => 'IZZ'],
                ['id' => 230, 'name' => 'Ohaozara',            'code' => 'OHZ'],
                ['id' => 231, 'name' => 'Ohaukwu',             'code' => 'OHK'],
                ['id' => 232, 'name' => 'Onicha',              'code' => 'ONC'],
            ],
            // Rivers (state 12) — 23 LGAs
            12 => [
                ['id' => 233, 'name' => 'Abua/Odual',          'code' => 'ABU'],
                ['id' => 234, 'name' => 'Ahoada East',         'code' => 'AHE'],
                ['id' => 235, 'name' => 'Ahoada West',         'code' => 'AHW'],
                ['id' => 236, 'name' => 'Akuku-Toru',          'code' => 'AKT'],
                ['id' => 237, 'name' => 'Andoni',              'code' => 'AND'],
                ['id' => 238, 'name' => 'Asari-Toru',          'code' => 'AST'],
                ['id' => 239, 'name' => 'Bonny',               'code' => 'BON'],
                ['id' => 240, 'name' => 'Degema',              'code' => 'DGM'],
                ['id' => 241, 'name' => 'Eleme',               'code' => 'ELM'],
                ['id' => 242, 'name' => 'Emuoha',              'code' => 'EMH'],
                ['id' => 243, 'name' => 'Etche',               'code' => 'ETC'],
                ['id' => 244, 'name' => 'Gokana',              'code' => 'GKN'],
                ['id' => 245, 'name' => 'Ikwerre',             'code' => 'IKW'],
                ['id' => 246, 'name' => 'Khana',               'code' => 'KHN'],
                ['id' => 247, 'name' => 'Obio/Akpor',          'code' => 'OBA'],
                ['id' => 248, 'name' => 'Ogba/Egbema/Ndoni',   'code' => 'OGN'],
                ['id' => 249, 'name' => 'Ogu/Bolo',            'code' => 'OGB'],
                ['id' => 250, 'name' => 'Okrika',              'code' => 'OKR'],
                ['id' => 251, 'name' => 'Omuma',               'code' => 'OMM'],
                ['id' => 252, 'name' => 'Opobo/Nkoro',         'code' => 'OPN'],
                ['id' => 253, 'name' => 'Oyigbo',              'code' => 'OYG'],
                ['id' => 254, 'name' => 'Port Harcourt',       'code' => 'PHC'],
                ['id' => 255, 'name' => 'Tai',                 'code' => 'TAI'],
            ],
            // Delta (state 13) — 25 LGAs
            13 => [
                ['id' => 256, 'name' => 'Aniocha North',       'code' => 'ANN'],
                ['id' => 257, 'name' => 'Aniocha South',       'code' => 'ANS'],
                ['id' => 258, 'name' => 'Bomadi',              'code' => 'BMD'],
                ['id' => 259, 'name' => 'Burutu',              'code' => 'BRT'],
                ['id' => 260, 'name' => 'Ethiope East',        'code' => 'ETE'],
                ['id' => 261, 'name' => 'Ethiope West',        'code' => 'ETW'],
                ['id' => 262, 'name' => 'Ika North East',      'code' => 'IKN'],
                ['id' => 263, 'name' => 'Ika South',           'code' => 'IKS'],
                ['id' => 264, 'name' => 'Isoko North',         'code' => 'ISN'],
                ['id' => 265, 'name' => 'Isoko South',         'code' => 'ISS'],
                ['id' => 266, 'name' => 'Ndokwa East',         'code' => 'NDE'],
                ['id' => 267, 'name' => 'Ndokwa West',         'code' => 'NDW'],
                ['id' => 268, 'name' => 'Okpe',                'code' => 'OKP'],
                ['id' => 269, 'name' => 'Oshimili North',      'code' => 'OSN'],
                ['id' => 270, 'name' => 'Oshimili South',      'code' => 'OSS'],
                ['id' => 271, 'name' => 'Patani',              'code' => 'PTN'],
                ['id' => 272, 'name' => 'Sapele',              'code' => 'SAP'],
                ['id' => 273, 'name' => 'Udu',                 'code' => 'UDU'],
                ['id' => 274, 'name' => 'Ughelli North',       'code' => 'UGN'],
                ['id' => 275, 'name' => 'Ughelli South',       'code' => 'UGS'],
                ['id' => 276, 'name' => 'Ukwuani',             'code' => 'UKW'],
                ['id' => 277, 'name' => 'Uvwie',               'code' => 'UVW'],
                ['id' => 278, 'name' => 'Warri North',         'code' => 'WRN'],
                ['id' => 279, 'name' => 'Warri South',         'code' => 'WRS'],
                ['id' => 280, 'name' => 'Warri South West',    'code' => 'WSW'],
            ],
            // Edo (state 14) — 18 LGAs
            14 => [
                ['id' => 281, 'name' => 'Akoko-Edo',           'code' => 'AKE'],
                ['id' => 282, 'name' => 'Egor',                'code' => 'EGR'],
                ['id' => 283, 'name' => 'Esan Central',        'code' => 'ESC'],
                ['id' => 284, 'name' => 'Esan North East',     'code' => 'ESN'],
                ['id' => 285, 'name' => 'Esan South East',     'code' => 'ESS'],
                ['id' => 286, 'name' => 'Esan West',           'code' => 'ESW'],
                ['id' => 287, 'name' => 'Etsako Central',      'code' => 'ETC'],
                ['id' => 288, 'name' => 'Etsako East',         'code' => 'ETE'],
                ['id' => 289, 'name' => 'Etsako West',         'code' => 'ETW'],
                ['id' => 290, 'name' => 'Igueben',             'code' => 'IGU'],
                ['id' => 291, 'name' => 'Ikpoba Okha',         'code' => 'IKP'],
                ['id' => 292, 'name' => 'Orhionmwon',         'code' => 'ORH'],
                ['id' => 293, 'name' => 'Oredo',               'code' => 'ORD'],
                ['id' => 294, 'name' => 'Ovia North East',     'code' => 'OVN'],
                ['id' => 295, 'name' => 'Ovia South West',     'code' => 'OVS'],
                ['id' => 296, 'name' => 'Owan East',           'code' => 'OWE'],
                ['id' => 297, 'name' => 'Owan West',           'code' => 'OWW'],
                ['id' => 298, 'name' => 'Uhunmwonde',          'code' => 'UHU'],
            ],
            // Cross River (state 15) — 18 LGAs
            15 => [
                ['id' => 299, 'name' => 'Abi',                 'code' => 'ABI'],
                ['id' => 300, 'name' => 'Akamkpa',             'code' => 'AKM'],
                ['id' => 301, 'name' => 'Akpabuyo',            'code' => 'AKP'],
                ['id' => 302, 'name' => 'Bakassi',             'code' => 'BKS'],
                ['id' => 303, 'name' => 'Bekwarra',            'code' => 'BKW'],
                ['id' => 304, 'name' => 'Biase',               'code' => 'BIS'],
                ['id' => 305, 'name' => 'Boki',                'code' => 'BOK'],
                ['id' => 306, 'name' => 'Calabar Municipal',   'code' => 'CLM'],
                ['id' => 307, 'name' => 'Calabar South',       'code' => 'CLS'],
                ['id' => 308, 'name' => 'Etung',               'code' => 'ETG'],
                ['id' => 309, 'name' => 'Ikom',                'code' => 'IKM'],
                ['id' => 310, 'name' => 'Obanliku',            'code' => 'OBL'],
                ['id' => 311, 'name' => 'Obubra',              'code' => 'OBB'],
                ['id' => 312, 'name' => 'Obudu',               'code' => 'OBD'],
                ['id' => 313, 'name' => 'Odukpani',            'code' => 'ODK'],
                ['id' => 314, 'name' => 'Ogoja',               'code' => 'OGJ'],
                ['id' => 315, 'name' => 'Yakuur',              'code' => 'YKR'],
                ['id' => 316, 'name' => 'Yala',                'code' => 'YLA'],
            ],
            // Akwa Ibom (state 16) — 31 LGAs
            16 => [
                ['id' => 317, 'name' => 'Abak',                'code' => 'ABK'],
                ['id' => 318, 'name' => 'Eastern Obolo',       'code' => 'EOB'],
                ['id' => 319, 'name' => 'Eket',                'code' => 'EKT'],
                ['id' => 320, 'name' => 'Esit Eket',           'code' => 'ESK'],
                ['id' => 321, 'name' => 'Essien Udim',         'code' => 'ESU'],
                ['id' => 322, 'name' => 'Etim Ekpo',           'code' => 'ETM'],
                ['id' => 323, 'name' => 'Etinan',              'code' => 'ETN'],
                ['id' => 324, 'name' => 'Ibeno',               'code' => 'IBN'],
                ['id' => 325, 'name' => 'Ibesikpo Asutan',     'code' => 'IBS'],
                ['id' => 326, 'name' => 'Ibiono-Ibom',         'code' => 'IBO'],
                ['id' => 327, 'name' => 'Ika',                 'code' => 'IKA'],
                ['id' => 328, 'name' => 'Ikono',               'code' => 'IKN'],
                ['id' => 329, 'name' => 'Ikot Abasi',          'code' => 'IKB'],
                ['id' => 330, 'name' => 'Ikot Ekpene',         'code' => 'IKE'],
                ['id' => 331, 'name' => 'Ini',                 'code' => 'INI'],
                ['id' => 332, 'name' => 'Itu',                 'code' => 'ITU'],
                ['id' => 333, 'name' => 'Mbo',                 'code' => 'MBO'],
                ['id' => 334, 'name' => 'Mkpat-Enin',         'code' => 'MKE'],
                ['id' => 335, 'name' => 'Nsit-Atai',           'code' => 'NSA'],
                ['id' => 336, 'name' => 'Nsit-Ibom',           'code' => 'NSI'],
                ['id' => 337, 'name' => 'Nsit-Ubium',         'code' => 'NSU'],
                ['id' => 338, 'name' => 'Obot Akara',          'code' => 'OBK'],
                ['id' => 339, 'name' => 'Okobo',               'code' => 'OKB'],
                ['id' => 340, 'name' => 'Onna',                'code' => 'ONN'],
                ['id' => 341, 'name' => 'Oron',                'code' => 'ORN'],
                ['id' => 342, 'name' => 'Oruk Anam',           'code' => 'ORA'],
                ['id' => 343, 'name' => 'Udung-Uko',           'code' => 'UDK'],
                ['id' => 344, 'name' => 'Ukanafun',            'code' => 'UKN'],
                ['id' => 345, 'name' => 'Uruan',               'code' => 'URN'],
                ['id' => 346, 'name' => 'Urue-Offong/Oruko',   'code' => 'URO'],
                ['id' => 347, 'name' => 'Uyo',                 'code' => 'UYO'],
            ],
            // Bayelsa (state 17) — 8 LGAs
            17 => [
                ['id' => 348, 'name' => 'Brass',               'code' => 'BRS'],
                ['id' => 349, 'name' => 'Ekeremor',            'code' => 'EKR'],
                ['id' => 350, 'name' => 'Kolokuma/Opokuma',    'code' => 'KLO'],
                ['id' => 351, 'name' => 'Nembe',               'code' => 'NMB'],
                ['id' => 352, 'name' => 'Ogbia',               'code' => 'OGB'],
                ['id' => 353, 'name' => 'Sagbama',             'code' => 'SGB'],
                ['id' => 354, 'name' => 'Southern Ijaw',       'code' => 'SIJ'],
                ['id' => 355, 'name' => 'Yenagoa',             'code' => 'YNG'],
            ],
            // Kaduna (state 18) — 23 LGAs
            18 => [
                ['id' => 356, 'name' => 'Birnin Gwari',        'code' => 'BNG'],
                ['id' => 357, 'name' => 'Chikun',              'code' => 'CHK'],
                ['id' => 358, 'name' => 'Giwa',                'code' => 'GWA'],
                ['id' => 359, 'name' => 'Igabi',               'code' => 'IGB'],
                ['id' => 360, 'name' => 'Ikara',               'code' => 'IKR'],
                ['id' => 361, 'name' => 'Jaba',                'code' => 'JBA'],
                ['id' => 362, 'name' => "Jema'a",              'code' => 'JMA'],
                ['id' => 363, 'name' => 'Kachia',              'code' => 'KAC'],
                ['id' => 364, 'name' => 'Kaduna North',        'code' => 'KDN'],
                ['id' => 365, 'name' => 'Kaduna South',        'code' => 'KDS'],
                ['id' => 366, 'name' => 'Kagarko',             'code' => 'KGR'],
                ['id' => 367, 'name' => 'Kajuru',              'code' => 'KJR'],
                ['id' => 368, 'name' => 'Kaura',               'code' => 'KRA'],
                ['id' => 369, 'name' => 'Kauru',               'code' => 'KRU'],
                ['id' => 370, 'name' => 'Kubau',               'code' => 'KBU'],
                ['id' => 371, 'name' => 'Kudan',               'code' => 'KDN'],
                ['id' => 372, 'name' => 'Lere',                'code' => 'LRE'],
                ['id' => 373, 'name' => 'Makarfi',             'code' => 'MKF'],
                ['id' => 374, 'name' => 'Sabon Gari',          'code' => 'SBG'],
                ['id' => 375, 'name' => 'Sanga',               'code' => 'SNG'],
                ['id' => 376, 'name' => 'Soba',                'code' => 'SBA'],
                ['id' => 377, 'name' => 'Zangon Kataf',        'code' => 'ZKT'],
                ['id' => 378, 'name' => 'Zaria',               'code' => 'ZAR'],
            ],
            // Kano (state 19) — 44 LGAs
            19 => [
                ['id' => 379, 'name' => 'Ajingi',              'code' => 'AJN'],
                ['id' => 380, 'name' => 'Albasu',              'code' => 'ALB'],
                ['id' => 381, 'name' => 'Bagwai',              'code' => 'BGW'],
                ['id' => 382, 'name' => 'Bebeji',              'code' => 'BBJ'],
                ['id' => 383, 'name' => 'Bichi',               'code' => 'BCH'],
                ['id' => 384, 'name' => 'Bunkure',             'code' => 'BNK'],
                ['id' => 385, 'name' => 'Dala',                'code' => 'DLA'],
                ['id' => 386, 'name' => 'Dambatta',            'code' => 'DMB'],
                ['id' => 387, 'name' => 'Dawakin Kudu',        'code' => 'DWK'],
                ['id' => 388, 'name' => 'Dawakin Tofa',        'code' => 'DWT'],
                ['id' => 389, 'name' => 'Doguwa',              'code' => 'DGW'],
                ['id' => 390, 'name' => 'Fagge',               'code' => 'FGG'],
                ['id' => 391, 'name' => 'Gabasawa',            'code' => 'GBS'],
                ['id' => 392, 'name' => 'Garko',               'code' => 'GRK'],
                ['id' => 393, 'name' => 'Garun Mallam',        'code' => 'GRM'],
                ['id' => 394, 'name' => 'Gaya',                'code' => 'GYA'],
                ['id' => 395, 'name' => 'Gezawa',              'code' => 'GZW'],
                ['id' => 396, 'name' => 'Gwale',               'code' => 'GWL'],
                ['id' => 397, 'name' => 'Gwarzo',              'code' => 'GWZ'],
                ['id' => 398, 'name' => 'Kabo',                'code' => 'KBO'],
                ['id' => 399, 'name' => 'Kano Municipal',      'code' => 'KNM'],
                ['id' => 400, 'name' => 'Karaye',              'code' => 'KRY'],
                ['id' => 401, 'name' => 'Kibiya',              'code' => 'KBY'],
                ['id' => 402, 'name' => 'Kiru',                'code' => 'KRU'],
                ['id' => 403, 'name' => 'Kumbotso',            'code' => 'KMB'],
                ['id' => 404, 'name' => 'Kunchi',              'code' => 'KNC'],
                ['id' => 405, 'name' => 'Kura',                'code' => 'KRA'],
                ['id' => 406, 'name' => 'Madobi',              'code' => 'MDB'],
                ['id' => 407, 'name' => 'Makoda',              'code' => 'MKD'],
                ['id' => 408, 'name' => 'Minjibir',            'code' => 'MJB'],
                ['id' => 409, 'name' => 'Nassarawa',           'code' => 'NSR'],
                ['id' => 410, 'name' => 'Rano',                'code' => 'RNO'],
                ['id' => 411, 'name' => 'Rimin Gado',          'code' => 'RGD'],
                ['id' => 412, 'name' => 'Rogo',                'code' => 'RGO'],
                ['id' => 413, 'name' => 'Shanono',             'code' => 'SHN'],
                ['id' => 414, 'name' => 'Sumaila',             'code' => 'SML'],
                ['id' => 415, 'name' => 'Takai',               'code' => 'TKI'],
                ['id' => 416, 'name' => 'Tarauni',             'code' => 'TRN'],
                ['id' => 417, 'name' => 'Tofa',                'code' => 'TFA'],
                ['id' => 418, 'name' => 'Tsanyawa',            'code' => 'TSN'],
                ['id' => 419, 'name' => 'Tudun Wada',          'code' => 'TDW'],
                ['id' => 420, 'name' => 'Ungogo',              'code' => 'UNG'],
                ['id' => 421, 'name' => 'Warawa',              'code' => 'WRW'],
                ['id' => 422, 'name' => 'Wudil',               'code' => 'WDL'],
            ],
            // Katsina (state 20) — 34 LGAs
            20 => [
                ['id' => 423, 'name' => 'Bakori',              'code' => 'BKR'],
                ['id' => 424, 'name' => 'Batagarawa',          'code' => 'BTG'],
                ['id' => 425, 'name' => 'Batsari',             'code' => 'BTS'],
                ['id' => 426, 'name' => 'Baure',               'code' => 'BRE'],
                ['id' => 427, 'name' => 'Bindawa',             'code' => 'BDW'],
                ['id' => 428, 'name' => 'Charanchi',           'code' => 'CRN'],
                ['id' => 429, 'name' => 'Dan Musa',            'code' => 'DNM'],
                ['id' => 430, 'name' => 'Dandume',             'code' => 'DDM'],
                ['id' => 431, 'name' => 'Danja',               'code' => 'DNJ'],
                ['id' => 432, 'name' => 'Daura',               'code' => 'DRA'],
                ['id' => 433, 'name' => 'Dutsi',               'code' => 'DTS'],
                ['id' => 434, 'name' => 'Dutsin Ma',           'code' => 'DTM'],
                ['id' => 435, 'name' => 'Faskari',             'code' => 'FSK'],
                ['id' => 436, 'name' => 'Funtua',              'code' => 'FTU'],
                ['id' => 437, 'name' => 'Ingawa',              'code' => 'IGW'],
                ['id' => 438, 'name' => 'Jibia',               'code' => 'JIB'],
                ['id' => 439, 'name' => 'Kafur',               'code' => 'KFR'],
                ['id' => 440, 'name' => 'Kaita',               'code' => 'KIT'],
                ['id' => 441, 'name' => 'Kankara',             'code' => 'KNK'],
                ['id' => 442, 'name' => 'Kankia',              'code' => 'KNI'],
                ['id' => 443, 'name' => 'Katsina',             'code' => 'KTS'],
                ['id' => 444, 'name' => 'Kurfi',               'code' => 'KRF'],
                ['id' => 445, 'name' => 'Kusada',              'code' => 'KSD'],
                ['id' => 446, 'name' => "Mai'Adua",            'code' => 'MAD'],
                ['id' => 447, 'name' => 'Malumfashi',          'code' => 'MLF'],
                ['id' => 448, 'name' => 'Mani',                'code' => 'MNI'],
                ['id' => 449, 'name' => 'Mashi',               'code' => 'MSH'],
                ['id' => 450, 'name' => 'Matazu',              'code' => 'MTZ'],
                ['id' => 451, 'name' => 'Musawa',              'code' => 'MSW'],
                ['id' => 452, 'name' => 'Rimi',                'code' => 'RMI'],
                ['id' => 453, 'name' => 'Sabuwa',              'code' => 'SBW'],
                ['id' => 454, 'name' => 'Safana',              'code' => 'SFN'],
                ['id' => 455, 'name' => 'Sandamu',             'code' => 'SDM'],
                ['id' => 456, 'name' => 'Zango',               'code' => 'ZNG'],
            ],
            // Jigawa (state 21) — 27 LGAs
            21 => [
                ['id' => 457, 'name' => 'Auyo',                'code' => 'AYO'],
                ['id' => 458, 'name' => 'Babura',              'code' => 'BBR'],
                ['id' => 459, 'name' => 'Biriniwa',            'code' => 'BRW'],
                ['id' => 460, 'name' => 'Birnin Kudu',         'code' => 'BKD'],
                ['id' => 461, 'name' => 'Buji',                'code' => 'BJI'],
                ['id' => 462, 'name' => 'Dutse',               'code' => 'DTS'],
                ['id' => 463, 'name' => 'Gagarawa',            'code' => 'GGW'],
                ['id' => 464, 'name' => 'Garki',               'code' => 'GRK'],
                ['id' => 465, 'name' => 'Gumel',               'code' => 'GML'],
                ['id' => 466, 'name' => 'Guri',                'code' => 'GRI'],
                ['id' => 467, 'name' => 'Gwaram',              'code' => 'GWM'],
                ['id' => 468, 'name' => 'Gwiwa',               'code' => 'GWW'],
                ['id' => 469, 'name' => 'Hadejia',             'code' => 'HDJ'],
                ['id' => 470, 'name' => 'Jahun',               'code' => 'JHN'],
                ['id' => 471, 'name' => 'Kafin Hausa',         'code' => 'KFH'],
                ['id' => 472, 'name' => 'Kaugama',             'code' => 'KGM'],
                ['id' => 473, 'name' => 'Kazaure',             'code' => 'KZR'],
                ['id' => 474, 'name' => 'Kiyawa',              'code' => 'KYW'],
                ['id' => 475, 'name' => 'Maigatari',           'code' => 'MGT'],
                ['id' => 476, 'name' => 'Malam Madori',        'code' => 'MMD'],
                ['id' => 477, 'name' => 'Miga',                'code' => 'MGA'],
                ['id' => 478, 'name' => 'Ringim',              'code' => 'RGM'],
                ['id' => 479, 'name' => 'Roni',                'code' => 'RNI'],
                ['id' => 480, 'name' => 'Sule Tankarkar',      'code' => 'STK'],
                ['id' => 481, 'name' => 'Taura',               'code' => 'TRA'],
                ['id' => 482, 'name' => 'Yankwashi',           'code' => 'YKW'],
                ['id' => 483, 'name' => 'Kafin Hausa',         'code' => 'KFH2'],
            ],
            // Kebbi (state 22) — 21 LGAs
            22 => [
                ['id' => 484, 'name' => 'Aleiro',              'code' => 'ALR'],
                ['id' => 485, 'name' => 'Arewa Dandi',         'code' => 'ARD'],
                ['id' => 486, 'name' => 'Argungu',             'code' => 'ARG'],
                ['id' => 487, 'name' => 'Augie',               'code' => 'AUG'],
                ['id' => 488, 'name' => 'Bagudo',              'code' => 'BGD'],
                ['id' => 489, 'name' => 'Birnin Kebbi',        'code' => 'BKB'],
                ['id' => 490, 'name' => 'Bunza',               'code' => 'BNZ'],
                ['id' => 491, 'name' => 'Dandi',               'code' => 'DND'],
                ['id' => 492, 'name' => 'Fakai',               'code' => 'FKI'],
                ['id' => 493, 'name' => 'Gwandu',              'code' => 'GWD'],
                ['id' => 494, 'name' => 'Jega',                'code' => 'JGA'],
                ['id' => 495, 'name' => 'Kalgo',               'code' => 'KLG'],
                ['id' => 496, 'name' => 'Koko/Besse',          'code' => 'KKB'],
                ['id' => 497, 'name' => 'Maiyama',             'code' => 'MYM'],
                ['id' => 498, 'name' => 'Ngaski',              'code' => 'NGS'],
                ['id' => 499, 'name' => 'Sakaba',              'code' => 'SKB'],
                ['id' => 500, 'name' => 'Shanga',              'code' => 'SHG'],
                ['id' => 501, 'name' => 'Suru',                'code' => 'SRU'],
                ['id' => 502, 'name' => 'Wasagu/Danko',        'code' => 'WSD'],
                ['id' => 503, 'name' => 'Yauri',               'code' => 'YRI'],
                ['id' => 504, 'name' => 'Zuru',                'code' => 'ZRU'],
            ],
            // Sokoto (state 23) — 23 LGAs
            23 => [
                ['id' => 505, 'name' => 'Binji',               'code' => 'BNJ'],
                ['id' => 506, 'name' => 'Bodinga',             'code' => 'BDG'],
                ['id' => 507, 'name' => 'Dange Shuni',         'code' => 'DGS'],
                ['id' => 508, 'name' => 'Gada',                'code' => 'GDA'],
                ['id' => 509, 'name' => 'Goronyo',             'code' => 'GRY'],
                ['id' => 510, 'name' => 'Gudu',                'code' => 'GDU'],
                ['id' => 511, 'name' => 'Gwadabawa',           'code' => 'GWB'],
                ['id' => 512, 'name' => 'Illela',              'code' => 'ILL'],
                ['id' => 513, 'name' => 'Isa',                 'code' => 'ISA'],
                ['id' => 514, 'name' => 'Kebbe',               'code' => 'KBB'],
                ['id' => 515, 'name' => 'Kware',               'code' => 'KWR'],
                ['id' => 516, 'name' => 'Rabah',               'code' => 'RBH'],
                ['id' => 517, 'name' => 'Sabon Birni',         'code' => 'SBN'],
                ['id' => 518, 'name' => 'Shagari',             'code' => 'SGR'],
                ['id' => 519, 'name' => 'Silame',              'code' => 'SLM'],
                ['id' => 520, 'name' => 'Sokoto North',        'code' => 'SKN'],
                ['id' => 521, 'name' => 'Sokoto South',        'code' => 'SKS'],
                ['id' => 522, 'name' => 'Tambuwal',            'code' => 'TMB'],
                ['id' => 523, 'name' => 'Tangaza',             'code' => 'TGZ'],
                ['id' => 524, 'name' => 'Tureta',              'code' => 'TRT'],
                ['id' => 525, 'name' => 'Wamako',              'code' => 'WMK'],
                ['id' => 526, 'name' => 'Wurno',               'code' => 'WRN'],
                ['id' => 527, 'name' => 'Yabo',                'code' => 'YBO'],
            ],
            // Zamfara (state 24) — 14 LGAs
            24 => [
                ['id' => 528, 'name' => 'Anka',                'code' => 'ANK'],
                ['id' => 529, 'name' => 'Bakura',              'code' => 'BKR'],
                ['id' => 530, 'name' => 'Birnin Magaji/Kiyaw', 'code' => 'BMK'],
                ['id' => 531, 'name' => 'Bukkuyum',            'code' => 'BKY'],
                ['id' => 532, 'name' => 'Bungudu',             'code' => 'BGD'],
                ['id' => 533, 'name' => 'Gummi',               'code' => 'GMM'],
                ['id' => 534, 'name' => 'Gusau',               'code' => 'GSU'],
                ['id' => 535, 'name' => 'Kaura Namoda',        'code' => 'KNM'],
                ['id' => 536, 'name' => 'Maradun',             'code' => 'MRD'],
                ['id' => 537, 'name' => 'Maru',                'code' => 'MRU'],
                ['id' => 538, 'name' => 'Shinkafi',            'code' => 'SNK'],
                ['id' => 539, 'name' => 'Talata Mafara',       'code' => 'TLM'],
                ['id' => 540, 'name' => 'Tsafe',               'code' => 'TSF'],
                ['id' => 541, 'name' => 'Zurmi',               'code' => 'ZRM'],
            ],
            // Adamawa (state 25) — 21 LGAs
            25 => [
                ['id' => 542, 'name' => 'Demsa',               'code' => 'DMS'],
                ['id' => 543, 'name' => 'Fufore',              'code' => 'FFR'],
                ['id' => 544, 'name' => 'Ganye',               'code' => 'GNY'],
                ['id' => 545, 'name' => 'Girei',               'code' => 'GRI'],
                ['id' => 546, 'name' => 'Gombi',               'code' => 'GMB'],
                ['id' => 547, 'name' => 'Guyuk',               'code' => 'GYK'],
                ['id' => 548, 'name' => 'Hong',                'code' => 'HNG'],
                ['id' => 549, 'name' => 'Jada',                'code' => 'JDA'],
                ['id' => 550, 'name' => 'Lamurde',             'code' => 'LMD'],
                ['id' => 551, 'name' => 'Madagali',            'code' => 'MDG'],
                ['id' => 552, 'name' => 'Maiha',               'code' => 'MIH'],
                ['id' => 553, 'name' => 'Mayo-Belwa',          'code' => 'MYB'],
                ['id' => 554, 'name' => 'Michika',             'code' => 'MCK'],
                ['id' => 555, 'name' => 'Mubi North',          'code' => 'MBN'],
                ['id' => 556, 'name' => 'Mubi South',          'code' => 'MBS'],
                ['id' => 557, 'name' => 'Numan',               'code' => 'NMN'],
                ['id' => 558, 'name' => 'Shelleng',            'code' => 'SLG'],
                ['id' => 559, 'name' => 'Song',                'code' => 'SNG'],
                ['id' => 560, 'name' => 'Toungo',              'code' => 'TNG'],
                ['id' => 561, 'name' => 'Yola North',          'code' => 'YLN'],
                ['id' => 562, 'name' => 'Yola South',          'code' => 'YLS'],
            ],
            // Bauchi (state 26) — 20 LGAs
            26 => [
                ['id' => 563, 'name' => 'Alkaleri',            'code' => 'ALK'],
                ['id' => 564, 'name' => 'Bauchi',              'code' => 'BAU'],
                ['id' => 565, 'name' => 'Bogoro',              'code' => 'BGR'],
                ['id' => 566, 'name' => 'Dambam',              'code' => 'DBM'],
                ['id' => 567, 'name' => 'Darazo',              'code' => 'DRZ'],
                ['id' => 568, 'name' => 'Dass',                'code' => 'DSS'],
                ['id' => 569, 'name' => 'Ganjuwa',             'code' => 'GJW'],
                ['id' => 570, 'name' => 'Giade',               'code' => 'GDE'],
                ['id' => 571, 'name' => 'Itas/Gadau',          'code' => 'ITG'],
                ['id' => 572, 'name' => "Jama'are",            'code' => 'JMR'],
                ['id' => 573, 'name' => 'Katagum',             'code' => 'KTG'],
                ['id' => 574, 'name' => 'Kirfi',               'code' => 'KRF'],
                ['id' => 575, 'name' => 'Misau',               'code' => 'MSU'],
                ['id' => 576, 'name' => 'Ningi',               'code' => 'NNG'],
                ['id' => 577, 'name' => 'Shira',               'code' => 'SHR'],
                ['id' => 578, 'name' => 'Tafawa Balewa',       'code' => 'TFB'],
                ['id' => 579, 'name' => 'Toro',                'code' => 'TRO'],
                ['id' => 580, 'name' => 'Warji',               'code' => 'WJI'],
                ['id' => 581, 'name' => 'Zaki',                'code' => 'ZKI'],
                ['id' => 582, 'name' => 'Darazo',              'code' => 'DRZ2'],
            ],
            // Borno (state 27) — 27 LGAs
            27 => [
                ['id' => 583, 'name' => 'Abadam',              'code' => 'ABD'],
                ['id' => 584, 'name' => 'Askira/Uba',          'code' => 'ASU'],
                ['id' => 585, 'name' => 'Bama',                'code' => 'BMA'],
                ['id' => 586, 'name' => 'Bayo',                'code' => 'BYO'],
                ['id' => 587, 'name' => 'Biu',                 'code' => 'BIU'],
                ['id' => 588, 'name' => 'Chibok',              'code' => 'CHB'],
                ['id' => 589, 'name' => 'Damboa',              'code' => 'DMB'],
                ['id' => 590, 'name' => 'Dikwa',               'code' => 'DKW'],
                ['id' => 591, 'name' => 'Gubio',               'code' => 'GBO'],
                ['id' => 592, 'name' => 'Guzamala',            'code' => 'GZM'],
                ['id' => 593, 'name' => 'Gwoza',               'code' => 'GWZ'],
                ['id' => 594, 'name' => 'Hawul',               'code' => 'HWL'],
                ['id' => 595, 'name' => 'Jere',                'code' => 'JRE'],
                ['id' => 596, 'name' => 'Kaga',                'code' => 'KGA'],
                ['id' => 597, 'name' => 'Kala/Balge',          'code' => 'KLB'],
                ['id' => 598, 'name' => 'Konduga',             'code' => 'KDG'],
                ['id' => 599, 'name' => 'Kukawa',              'code' => 'KKW'],
                ['id' => 600, 'name' => 'Kwaya Kusar',         'code' => 'KWK'],
                ['id' => 601, 'name' => 'Mafa',                'code' => 'MFA'],
                ['id' => 602, 'name' => 'Magumeri',            'code' => 'MGM'],
                ['id' => 603, 'name' => 'Maiduguri',           'code' => 'MDG'],
                ['id' => 604, 'name' => 'Marte',               'code' => 'MRT'],
                ['id' => 605, 'name' => 'Mobbar',              'code' => 'MBR'],
                ['id' => 606, 'name' => 'Monguno',             'code' => 'MNG'],
                ['id' => 607, 'name' => 'Ngala',               'code' => 'NGL'],
                ['id' => 608, 'name' => 'Nganzai',             'code' => 'NGZ'],
                ['id' => 609, 'name' => 'Shani',               'code' => 'SHN'],
            ],
            // Gombe (state 28) — 11 LGAs
            28 => [
                ['id' => 610, 'name' => 'Akko',                'code' => 'AKO'],
                ['id' => 611, 'name' => 'Balanga',             'code' => 'BLG'],
                ['id' => 612, 'name' => 'Billiri',             'code' => 'BLR'],
                ['id' => 613, 'name' => 'Dukku',               'code' => 'DKU'],
                ['id' => 614, 'name' => 'Funakaye',            'code' => 'FNK'],
                ['id' => 615, 'name' => 'Gombe',               'code' => 'GMB'],
                ['id' => 616, 'name' => 'Kaltungo',            'code' => 'KTG'],
                ['id' => 617, 'name' => 'Kwami',               'code' => 'KWM'],
                ['id' => 618, 'name' => 'Nafada',              'code' => 'NFD'],
                ['id' => 619, 'name' => 'Shomgom',             'code' => 'SHG'],
                ['id' => 620, 'name' => 'Yamaltu/Deba',        'code' => 'YMD'],
            ],
            // Taraba (state 29) — 16 LGAs
            29 => [
                ['id' => 621, 'name' => 'Ardo Kola',           'code' => 'ADK'],
                ['id' => 622, 'name' => 'Bali',                'code' => 'BLI'],
                ['id' => 623, 'name' => 'Donga',               'code' => 'DNG'],
                ['id' => 624, 'name' => 'Gashaka',             'code' => 'GSK'],
                ['id' => 625, 'name' => 'Gasso',               'code' => 'GSO'],
                ['id' => 626, 'name' => 'Ibi',                 'code' => 'IBI'],
                ['id' => 627, 'name' => 'Jalingo',             'code' => 'JLG'],
                ['id' => 628, 'name' => 'Karim Lamido',        'code' => 'KRL'],
                ['id' => 629, 'name' => 'Kumi',                'code' => 'KMI'],
                ['id' => 630, 'name' => 'Lau',                 'code' => 'LAU'],
                ['id' => 631, 'name' => 'Sardauna',            'code' => 'SRD'],
                ['id' => 632, 'name' => 'Takum',               'code' => 'TKM'],
                ['id' => 633, 'name' => 'Ussa',                'code' => 'USA'],
                ['id' => 634, 'name' => 'Wukari',              'code' => 'WKR'],
                ['id' => 635, 'name' => 'Yorro',               'code' => 'YRO'],
                ['id' => 636, 'name' => 'Zing',                'code' => 'ZNG'],
            ],
            // Yobe (state 30) — 17 LGAs
            30 => [
                ['id' => 637, 'name' => 'Bade',                'code' => 'BDE'],
                ['id' => 638, 'name' => 'Bursari',             'code' => 'BRS'],
                ['id' => 639, 'name' => 'Damaturu',            'code' => 'DMT'],
                ['id' => 640, 'name' => 'Fika',                'code' => 'FKA'],
                ['id' => 641, 'name' => 'Fune',                'code' => 'FNE'],
                ['id' => 642, 'name' => 'Geidam',              'code' => 'GDM'],
                ['id' => 643, 'name' => 'Gujba',               'code' => 'GJB'],
                ['id' => 644, 'name' => 'Gulani',              'code' => 'GLN'],
                ['id' => 645, 'name' => 'Jakusko',             'code' => 'JKS'],
                ['id' => 646, 'name' => 'Karasuwa',            'code' => 'KRS'],
                ['id' => 647, 'name' => 'Machina',             'code' => 'MCN'],
                ['id' => 648, 'name' => 'Nangere',             'code' => 'NNG'],
                ['id' => 649, 'name' => 'Nguru',               'code' => 'NGR'],
                ['id' => 650, 'name' => 'Potiskum',            'code' => 'PTK'],
                ['id' => 651, 'name' => 'Tarmua',              'code' => 'TRM'],
                ['id' => 652, 'name' => 'Yunusari',            'code' => 'YNS'],
                ['id' => 653, 'name' => 'Yusufari',            'code' => 'YSF'],
            ],
            // Benue (state 31) — 23 LGAs
            31 => [
                ['id' => 654, 'name' => 'Ado',                 'code' => 'ADO'],
                ['id' => 655, 'name' => 'Agatu',               'code' => 'AGT'],
                ['id' => 656, 'name' => 'Apa',                 'code' => 'APA'],
                ['id' => 657, 'name' => 'Buruku',              'code' => 'BRK'],
                ['id' => 658, 'name' => 'Gboko',               'code' => 'GBK'],
                ['id' => 659, 'name' => 'Guma',                'code' => 'GMA'],
                ['id' => 660, 'name' => 'Gwer East',           'code' => 'GWE'],
                ['id' => 661, 'name' => 'Gwer West',           'code' => 'GWW'],
                ['id' => 662, 'name' => 'Katsina-Ala',         'code' => 'KTA'],
                ['id' => 663, 'name' => 'Konshisha',           'code' => 'KNS'],
                ['id' => 664, 'name' => 'Kwande',              'code' => 'KWD'],
                ['id' => 665, 'name' => 'Logo',                'code' => 'LGO'],
                ['id' => 666, 'name' => 'Makurdi',             'code' => 'MKD'],
                ['id' => 667, 'name' => 'Obi',                 'code' => 'OBI'],
                ['id' => 668, 'name' => 'Ogbadibo',            'code' => 'OGB'],
                ['id' => 669, 'name' => 'Ohimini',             'code' => 'OHM'],
                ['id' => 670, 'name' => 'Oju',                 'code' => 'OJU'],
                ['id' => 671, 'name' => 'Okpokwu',             'code' => 'OKP'],
                ['id' => 672, 'name' => 'Otukpo',              'code' => 'OTK'],
                ['id' => 673, 'name' => 'Tarka',               'code' => 'TRK'],
                ['id' => 674, 'name' => 'Ukum',                'code' => 'UKM'],
                ['id' => 675, 'name' => 'Ushongo',             'code' => 'USH'],
                ['id' => 676, 'name' => 'Vandeikya',           'code' => 'VDK'],
            ],
            // FCT (state 32) — 6 Area Councils
            32 => [
                ['id' => 677, 'name' => 'Abaji',               'code' => 'ABJ'],
                ['id' => 678, 'name' => 'Bwari',               'code' => 'BWR'],
                ['id' => 679, 'name' => 'Gwagwalada',          'code' => 'GWG'],
                ['id' => 680, 'name' => 'Kuje',                'code' => 'KJE'],
                ['id' => 681, 'name' => 'Kwali',               'code' => 'KWL'],
                ['id' => 682, 'name' => 'Municipal Area Council','code' => 'MAC'],
            ],
            // Kogi (state 33) — 21 LGAs
            33 => [
                ['id' => 683, 'name' => 'Adavi',               'code' => 'ADV'],
                ['id' => 684, 'name' => 'Ajaokuta',            'code' => 'AJK'],
                ['id' => 685, 'name' => 'Ankpa',               'code' => 'ANP'],
                ['id' => 686, 'name' => 'Bassa',               'code' => 'BSA'],
                ['id' => 687, 'name' => 'Dekina',              'code' => 'DKN'],
                ['id' => 688, 'name' => 'Ibaji',               'code' => 'IBJ'],
                ['id' => 689, 'name' => 'Igalamela Odolu',     'code' => 'IGO'],
                ['id' => 690, 'name' => 'Ijumu',               'code' => 'IJM'],
                ['id' => 691, 'name' => 'Kabba/Bunu',          'code' => 'KBB'],
                ['id' => 692, 'name' => 'Kogi',                'code' => 'KGI'],
                ['id' => 693, 'name' => 'Lokoja',              'code' => 'LKJ'],
                ['id' => 694, 'name' => 'Mopa Muro',           'code' => 'MPM'],
                ['id' => 695, 'name' => 'Ofu',                 'code' => 'OFU'],
                ['id' => 696, 'name' => 'Ogori/Magongo',       'code' => 'OGM'],
                ['id' => 697, 'name' => 'Okehi',               'code' => 'OKH'],
                ['id' => 698, 'name' => 'Okene',               'code' => 'OKN'],
                ['id' => 699, 'name' => 'Olamaboro',           'code' => 'OLM'],
                ['id' => 700, 'name' => 'Omala',               'code' => 'OML'],
                ['id' => 701, 'name' => 'Yagba East',          'code' => 'YGE'],
                ['id' => 702, 'name' => 'Yagba West',          'code' => 'YGW'],
                ['id' => 703, 'name' => 'Mopa Muro',           'code' => 'MPM2'],
            ],
            // Kwara (state 34) — 16 LGAs
            34 => [
                ['id' => 704, 'name' => 'Asa',                 'code' => 'ASA'],
                ['id' => 705, 'name' => 'Baruten',             'code' => 'BRT'],
                ['id' => 706, 'name' => 'Edu',                 'code' => 'EDU'],
                ['id' => 707, 'name' => 'Ekiti',               'code' => 'EKT'],
                ['id' => 708, 'name' => 'Ifelodun',            'code' => 'IFD'],
                ['id' => 709, 'name' => 'Ilorin East',         'code' => 'ILE'],
                ['id' => 710, 'name' => 'Ilorin South',        'code' => 'ILS'],
                ['id' => 711, 'name' => 'Ilorin West',         'code' => 'ILW'],
                ['id' => 712, 'name' => 'Irepodun',            'code' => 'IRP'],
                ['id' => 713, 'name' => 'Isin',                'code' => 'ISN'],
                ['id' => 714, 'name' => 'Kaiama',              'code' => 'KIM'],
                ['id' => 715, 'name' => 'Moro',                'code' => 'MRO'],
                ['id' => 716, 'name' => 'Offa',                'code' => 'OFA'],
                ['id' => 717, 'name' => 'Oke Ero',             'code' => 'OKR'],
                ['id' => 718, 'name' => 'Oyun',                'code' => 'OYN'],
                ['id' => 719, 'name' => 'Pategi',              'code' => 'PTG'],
            ],
            // Nasarawa (state 35) — 13 LGAs
            35 => [
                ['id' => 720, 'name' => 'Akwanga',             'code' => 'AKW'],
                ['id' => 721, 'name' => 'Awe',                 'code' => 'AWE'],
                ['id' => 722, 'name' => 'Doma',                'code' => 'DMA'],
                ['id' => 723, 'name' => 'Karu',                'code' => 'KRU'],
                ['id' => 724, 'name' => 'Keana',               'code' => 'KNA'],
                ['id' => 725, 'name' => 'Keffi',               'code' => 'KFF'],
                ['id' => 726, 'name' => 'Kokona',              'code' => 'KKN'],
                ['id' => 727, 'name' => 'Lafia',               'code' => 'LFA'],
                ['id' => 728, 'name' => 'Nasarawa',            'code' => 'NSR'],
                ['id' => 729, 'name' => 'Nasarawa Egon',       'code' => 'NSE'],
                ['id' => 730, 'name' => 'Obi',                 'code' => 'OBI'],
                ['id' => 731, 'name' => 'Toto',                'code' => 'TTO'],
                ['id' => 732, 'name' => 'Wamba',               'code' => 'WMB'],
            ],
            // Niger (state 36) — 25 LGAs
            36 => [
                ['id' => 733, 'name' => 'Agaie',               'code' => 'AGE'],
                ['id' => 734, 'name' => 'Agwara',              'code' => 'AGW'],
                ['id' => 735, 'name' => 'Bida',                'code' => 'BDA'],
                ['id' => 736, 'name' => 'Borgu',               'code' => 'BRG'],
                ['id' => 737, 'name' => 'Bosso',               'code' => 'BSO'],
                ['id' => 738, 'name' => 'Chanchaga',           'code' => 'CCG'],
                ['id' => 739, 'name' => 'Edati',               'code' => 'EDT'],
                ['id' => 740, 'name' => 'Gbako',               'code' => 'GBK'],
                ['id' => 741, 'name' => 'Gurara',              'code' => 'GRR'],
                ['id' => 742, 'name' => 'Katcha',              'code' => 'KTC'],
                ['id' => 743, 'name' => 'Kontagora',           'code' => 'KTG'],
                ['id' => 744, 'name' => 'Lapai',               'code' => 'LPI'],
                ['id' => 745, 'name' => 'Lavun',               'code' => 'LVN'],
                ['id' => 746, 'name' => 'Magama',              'code' => 'MGM'],
                ['id' => 747, 'name' => 'Mariga',              'code' => 'MRG'],
                ['id' => 748, 'name' => 'Mashegu',             'code' => 'MSG'],
                ['id' => 749, 'name' => 'Mokwa',               'code' => 'MKW'],
                ['id' => 750, 'name' => 'Munya',               'code' => 'MNY'],
                ['id' => 751, 'name' => 'Paikoro',             'code' => 'PKR'],
                ['id' => 752, 'name' => 'Rafi',                'code' => 'RFI'],
                ['id' => 753, 'name' => 'Rijau',               'code' => 'RJU'],
                ['id' => 754, 'name' => 'Shiroro',             'code' => 'SHR'],
                ['id' => 755, 'name' => 'Suleja',              'code' => 'SLJ'],
                ['id' => 756, 'name' => 'Tafa',                'code' => 'TFA'],
                ['id' => 757, 'name' => 'Wushishi',            'code' => 'WSH'],
            ],
            // Plateau (state 37) — 17 LGAs
            37 => [
                ['id' => 758, 'name' => 'Barkin Ladi',         'code' => 'BKL'],
                ['id' => 759, 'name' => 'Bassa',               'code' => 'BSA'],
                ['id' => 760, 'name' => 'Bokkos',              'code' => 'BKS'],
                ['id' => 761, 'name' => 'Jos East',            'code' => 'JSE'],
                ['id' => 762, 'name' => 'Jos North',           'code' => 'JSN'],
                ['id' => 763, 'name' => 'Jos South',           'code' => 'JSS'],
                ['id' => 764, 'name' => 'Kanam',               'code' => 'KNM'],
                ['id' => 765, 'name' => 'Kanke',               'code' => 'KNK'],
                ['id' => 766, 'name' => 'Langtang North',      'code' => 'LTN'],
                ['id' => 767, 'name' => 'Langtang South',      'code' => 'LTS'],
                ['id' => 768, 'name' => 'Mangu',               'code' => 'MNG'],
                ['id' => 769, 'name' => 'Mikang',              'code' => 'MKG'],
                ['id' => 770, 'name' => 'Pankshin',            'code' => 'PKS'],
                ['id' => 771, 'name' => "Qua'an Pan",          'code' => 'QPN'],
                ['id' => 772, 'name' => 'Riyom',               'code' => 'RYM'],
                ['id' => 773, 'name' => 'Shendam',             'code' => 'SHD'],
                ['id' => 774, 'name' => 'Wase',                'code' => 'WSE'],
            ],
        ];

        $allLgas = [];
        foreach ($lgasByState as $stateId => $lgas) {
            foreach ($lgas as $lga) {
                $lga['state_id']   = $stateId;
                $lga['address']    = $lga['address'] ?? ($lga['name'] . ' Local Government Area Secretariat');
                $lga['created_at'] = now();
                $lga['updated_at'] = now();
                $allLgas[]         = $lga;
            }
        }
        DB::table('lgas')->upsert($allLgas, ['id'], ['state_id', 'name', 'code', 'address', 'updated_at']);

        // ── Wards (Ayobo Ipaja LCDA wards, lga_id=1 = Alimosho) ─────────────
        $wards = [
            ['id' => 1, 'lga_id' => 1, 'name' => 'Ayobo I Ward',      'code' => 'AYB1'],
            ['id' => 2, 'lga_id' => 1, 'name' => 'Ayobo II Ward',     'code' => 'AYB2'],
            ['id' => 3, 'lga_id' => 1, 'name' => 'Ipaja I Ward',      'code' => 'IPJ1'],
            ['id' => 4, 'lga_id' => 1, 'name' => 'Ipaja II Ward',     'code' => 'IPJ2'],
            ['id' => 5, 'lga_id' => 1, 'name' => 'Meiran Ward',       'code' => 'MERN'],
            ['id' => 6, 'lga_id' => 1, 'name' => 'Ekoro Ward',        'code' => 'EKRO'],
            ['id' => 7, 'lga_id' => 1, 'name' => 'Abule Egba Ward',   'code' => 'ABEG'],
            ['id' => 8, 'lga_id' => 1, 'name' => 'Ijaiye Ward',       'code' => 'IJYE'],
            ['id' => 9, 'lga_id' => 1, 'name' => 'Alagbado Ward',     'code' => 'ALGB'],
            ['id'=>10, 'lga_id' => 1, 'name' => 'Ile Epo Ward',       'code' => 'ILEP'],
        ];
        foreach ($wards as &$ward) {
            $ward['created_at'] = now();
            $ward['updated_at'] = now();
        }
        DB::table('wards')->upsert($wards, ['id'], ['lga_id', 'name', 'code', 'updated_at']);

        $this->command->info('Geography seeded: 37 states, 774+ LGAs, 10 Ayobo Ipaja wards.');
    }
}
